export default {
  CONFIG_BREED: 'CONFIG_BREED',
  CONFIG_GOAL: 'CONFIG_GOAL',
  CONFIG_SEX: 'CONFIG_SEX',
  CONFIG_AGE: 'CONFIG_AGE',
  CONFIG_REGISTRATION: 'CONFIG_REGISTRATION',
  GET_CONFIG_DATA_LOADING: 'GET_CONFIG_DATA_LOADING',
  GET_CONFIG_DATA_SUCCESS: 'GET_CONFIG_DATA_SUCCESS',
  GET_CONFIG_DATA_FAILURE: 'GET_CONFIG_DATA_FAILURE',
  SORT_BREEDS_BY_POPULAR: 'SORT_BREEDS_BY_POPULAR',
  SORT_BREEDS_BY_ALPHABET: 'SORT_BREEDS_BY_ALPHABET',
};
